// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookapi_minimal.AppContext;

#nullable disable

namespace bookapi_minimal.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookapi")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bookapi_minimal.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", "bookapi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00f8ce42-8148-40a8-8222-ab592ef7520b"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("8a95278f-0a0e-4f02-a5ab-24456b391fbf"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("35aaeb5f-50f6-4b16-95cd-2ac6380ff94d"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        },
                        new
                        {
                            Id = new Guid("9c7b0fc3-138f-4aa2-93ac-cd78fc6ef34a"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("d01bd94f-4aa0-4d2b-b252-5b75a6464de9"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("93108a87-e793-403f-a7eb-8aacbe2fab85"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
